trigger:
- master

pool:
  vmImage: Hosted Windows 2019 with VS2019

steps:
- task: giuliovdev.hugo-extension.hugo-build-task.HugoTask@1
  displayName: 'Hugo Generate '
  inputs:
    destination: '$(Build.ArtifactStagingDirectory)'
    extendedVersion: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
