trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: giuliovdev.hugo-extension.hugo-build-task.HugoTask@1
  displayName: 'Hugo Generate '
  inputs:
    destination: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
