trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: monachus/hugo

steps:
- script: hugo --source $(Build.SourcesDirectory) --destination $(Build.ArtifactStagingDirectory)  --enableGitInfo --i18n-warnings --verbose
  displayName: 'Publish Artifact: drop'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
